### ISSUE TITLE
When I load a tres file into an animated sprite, the png file is not loaded.

### ISSUE THREAD

**Issue by NounKim** [Jordyfel/duelyst-animated-sprites-godot#1]
In all kinds of tres files, I get the following warning.

scene/resources/resource_format_text.cpp:448 - res://addons/duelyst_animated_sprites/assets/spriteframes/units/boss_andromeda.tres:3 - ext_resource, invalid UUID: uid://b3vf3ld0o1ad2 - using text path instead: res://addons/duelyst_animated_sprites/assets/spritesheets/units/boss_andromeda.png

**Comment by Jordyfel** [comment]
That should not prevent the resource from loading properly, unless you moved the files to a different directory. If you didn't move the files, please describe the problem in more detail, or screenshot it.

**Comment by NounKim** [comment]
I cloned your project and used godot 4.0 version.

![image](https://user-images.githubusercontent.com/22708508/221074915-62141605-ecba-4792-a089-33f1985d21ba.png)

I dropped tres file to animated sprite2d.

![image](https://user-images.githubusercontent.com/22708508/221075044-03e33281-8224-4cc0-8fcd-99e809513fb6.png)

but frames are empty.

![image](https://user-images.githubusercontent.com/22708508/221075174-369e0b93-049c-4756-afb2-f856bcd670d3.png)

![image](https://user-images.githubusercontent.com/22708508/221075837-9557ced7-d9af-430b-87bf-4028d25ae5b2.png)
png files are exist on .tres file text path. [res://addons/duelyst_animated_sprites/assets/spritesheets/units/boss_andromeda.png]
![image](https://user-images.githubusercontent.com/22708508/221076000-8cf2f7cf-e72a-4e3e-9088-f78f6c9c38e7.png)


As an aside, is it possible to use the tres file in the 3.5 version?

**Comment by Jordyfel** [comment]
Sadly, I'm failing to reproduce the issue, so I have no idea what might be going on. I still get the error messages, they are expected, but the Spriteframes resource works.

I recommend trying to download it from the asset library in a brand new project to remove as many external variables. If that doesn't work, I've got nothing. Name in the asset library is "Duelyst Animated Sprites".

Also, the resources are not usable in 3.5, since they were saved with 4.0.
